languageCode = "en-us"
theme = "internet-weblog"
title = "Personal blog"
baseurl = "http://kostenko.name/"
publishDir = "docs"
[author]
    Handle = "gugu"
    FirstName = "Andrii"
    LastName = "Kostenko"
    Location = "Helsinki, Finland"
[blockfriday]
    extansions = ["hardLineBreak", "autolinking"]
